/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asiri_gram;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author thishantj
 */
public class Add_scale extends javax.swing.JFrame {

    /**
     * Creates new form Add_delete_shop
     */
    public Add_scale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnhome = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel_firstName = new javax.swing.JLabel();
        txtscalename = new javax.swing.JTextField();
        jLabel_lastName = new javax.swing.JLabel();
        txtscaleid = new javax.swing.JTextField();
        jLabel_dob = new javax.swing.JLabel();
        jLabel_parentName = new javax.swing.JLabel();
        cmblocation = new javax.swing.JComboBox();
        cmbstatus = new javax.swing.JComboBox();
        btnsave = new javax.swing.JButton();
        jLabel_parentName1 = new javax.swing.JLabel();
        cmblicensestatus = new javax.swing.JComboBox();
        jLabel_firstName1 = new javax.swing.JLabel();
        jLabel_firstName2 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 231, 227));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnhome.setBackground(new java.awt.Color(255, 255, 255));
        btnhome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white home.png"))); // NOI18N
        btnhome.setText("  Home");
        btnhome.setBorder(null);
        btnhome.setBorderPainted(false);
        btnhome.setContentAreaFilled(false);
        btnhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhome.setFocusPainted(false);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(255, 255, 255));
        btnexit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white exit.png"))); // NOI18N
        btnexit.setText("  Exit");
        btnexit.setBorder(null);
        btnexit.setBorderPainted(false);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnhome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
            .addComponent(btnexit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_firstName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_firstName.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_firstName.setText("Scale name : ");
        jPanel10.add(jLabel_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        txtscalename.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel10.add(txtscalename, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 750, 50));

        jLabel_lastName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_lastName.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_lastName.setText("Scale ID : ");
        jPanel10.add(jLabel_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        txtscaleid.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtscaleid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtscaleidActionPerformed(evt);
            }
        });
        jPanel10.add(txtscaleid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 750, 50));

        jLabel_dob.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_dob.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_dob.setText("Current location : ");
        jPanel10.add(jLabel_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, -1, -1));

        jLabel_parentName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_parentName.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_parentName.setText("Status");
        jPanel10.add(jLabel_parentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        cmblocation.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cmblocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stores", "Factory", "IDH", "Eriyawetiya", "Kiribathgoda", "Makola", "Mawaramandiya", "Delgoda", "Kokiskade", "Baththaramulla", "Athurugiriya", "Hendala", "Weliweriya", "Homagama", "Dalugama", "Wenappuwa", "Nagahamula", "Weyangoda", "Maligawatta", "Kaduwela", "Malabe", "Biyagama", "Kolonnawa", "Arangala", "Welisara", "Nugegoda", "Minuwangoda", "Kandana", "Arcade", " ", " " }));
        jPanel10.add(cmblocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 750, 50));

        cmbstatus.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Working", "New", "Broken", "Repairing", "Repaired", " " }));
        jPanel10.add(cmbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 750, 50));

        btnsave.setBackground(new java.awt.Color(109, 235, 231));
        btnsave.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-save-40.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel10.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 680, 140, 50));

        jLabel_parentName1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_parentName1.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_parentName1.setText("License status");
        jPanel10.add(jLabel_parentName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        cmblicensestatus.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cmblicensestatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Licensed", "Not licensed" }));
        jPanel10.add(cmblicensestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 750, 50));

        jLabel_firstName1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_firstName1.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_firstName1.setText("Purchase date :");
        jPanel10.add(jLabel_firstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));
        jLabel_firstName1.getAccessibleContext().setAccessibleName("Purchase date : ");

        jLabel_firstName2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel_firstName2.setForeground(new java.awt.Color(132, 132, 132));
        jLabel_firstName2.setText("Price :");
        jPanel10.add(jLabel_firstName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        txtprice.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpriceKeyTyped(evt);
            }
        });
        jPanel10.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 750, 50));

        jdate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel10.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 750, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        Homepage h = new Homepage();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int returnValue = 0;
    	returnValue = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Are you sure?", JOptionPane.YES_NO_OPTION);
    		
    	if (returnValue == JOptionPane.YES_OPTION)
    		System.exit(0);   
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtscaleidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtscaleidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtscaleidActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

           try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=asiri;user=admin;password=123456");
            
            if(txtscaleid.getText().isEmpty() && txtscalename.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter missing fields", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(txtscaleid.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter an ID", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(txtscalename.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter a name", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
            
            String query = "insert into scales(scaleID, scalename, pdate, price, lstatus, status, location) values(?,?,?,?,?,?,?)";
            
            PreparedStatement pst = conn.prepareStatement(query);
            
            pst.setString(1, txtscaleid.getText() );
            pst.setString(2, txtscalename.getText() );
            pst.setString(3, new SimpleDateFormat("MMM d, yyyy").format(jdate.getDate() ) );
            pst.setString(4, txtprice.getText() );
            pst.setString(5, cmblicensestatus.getSelectedItem().toString() );
            pst.setString(6, cmbstatus.getSelectedItem().toString() );
            pst.setString(7, cmblocation.getSelectedItem().toString() );
           
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Saved successfully");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyTyped
        
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c) && !evt.isAltDown() )
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtpriceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_scale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_scale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_scale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_scale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_scale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox cmblicensestatus;
    private javax.swing.JComboBox cmblocation;
    private javax.swing.JComboBox cmbstatus;
    private javax.swing.JLabel jLabel_dob;
    private javax.swing.JLabel jLabel_firstName;
    private javax.swing.JLabel jLabel_firstName1;
    private javax.swing.JLabel jLabel_firstName2;
    private javax.swing.JLabel jLabel_lastName;
    private javax.swing.JLabel jLabel_parentName;
    private javax.swing.JLabel jLabel_parentName1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtscaleid;
    private javax.swing.JTextField txtscalename;
    // End of variables declaration//GEN-END:variables
}
